<?php


function university_menu(){

  $items['ajax/university/path/%'] = array(
    'page callback' => 'university_ajax_callback',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('get ajax'),
    'delivery callback' => 'ajax_deliver',
  );

  $items['ajax/newsletter/path/%'] = array(
    'page callback' => 'university_ajax_newsletter_callback',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('get ajax'),
    'delivery callback' => 'ajax_deliver',
  );

  return $items;
}

function university_ajax_callback($nid, $type = 'ajax'){
  $_SESSION['nid'] = $nid;
  $viewName = 'introduction_to_law_and_methodology_nr'; 
  $viewInstructors = 'curriculum_instructors';
  $view_html = views_embed_view($viewName, $display_id = 'default');
  $view_instr = views_embed_view($viewInstructors, $display_id = 'default');
  $commands[] = ajax_command_replace('.view-introduction-to-law-and-methodology-nr', $view_html);
  $commands[] = ajax_command_replace('.view-curriculum-instructors', $view_instr);
  return array('#type' => 'ajax', '#commands' => $commands);
}

function university_ajax_newsletter_callback($nid, $type = 'ajax'){
  $_SESSION['ncvid'] = $nid;
  $viewName = 'newsletter_view'; 
  $view_html = views_embed_view($viewName, $display_id = 'default');
  $commands[] = ajax_command_replace('.view-newsletter-view', $view_html);
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
*Implements hook_block_info
*/
function university_block_info() {
  
  $blocks['custom_footer'] = array(
    'info' => t('Footer custom block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['search_button'] = array(
    'info' => t('Button search'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['slogan_near_logo'] = array(
    'info' => t('Slogan near logo'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['search_courses'] = array(
    'info' => t('Red Block - Search Courses'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['alumni_things'] = array(
    'info' => t('Alumni things block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['about_right_block'] = array(
    'info' => t('About custom right block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['sort_people_block'] = array(
    'info' => t('Sort People near breadcrumbs'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['contact_left_side'] = array(
    'info' => t('Contact left side vehicle'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;

}

function university_block_view($delta = '') {
  $block = array();

  switch ($delta) { 

    case 'contact_left_side':

      ctools_include('modal');
      ctools_include('ajax');
      ctools_modal_add_js();

      $block['subject'] = t('Contact Left Side (Custom)');
      $block['content'] = array(
        '#theme' => 'block_contact_left_side',
      );
    break;  

    case 'custom_footer':
      $block['subject'] = t('Footer Custom');
      $block['content'] = array(
        '#theme' => 'footer',
      );
    break;

    case 'search_button':
      $block['subject'] = t('Footer Custom');
      $block['content'] = array(
        '#theme' => 'bs',
      );
    break;

    case 'slogan_near_logo':
      $block['subject'] = t('Slogan');
      $block['content'] = array(
        '#theme' => 'slogan',
      );
    break;

    case 'search_courses':
      $block['subject'] = t('Course Finder');
      $block['content'] = array(
        '#theme' => 'block_course_finder',
      );
    break;

    case 'alumni_things':
      $block['subject'] = t('alumni things');
      $block['content'] = array(
        '#theme' => 'block_alumni_things',
      );
    break;

    case 'about_right_block':
      $block['subject'] = t('Member Organizations');
      $block['content'] = array(
        '#theme' => 'block_about_right',
      );
    break;

    case 'sort_people_block':
      $block['subject'] = t('Sort: ');
      $block['content'] = array(
        '#theme' => 'block_sort_people',
      );
    break;

  }
  return $block;
}

function university_theme() {

  $themes = array();

  $themes['footer'] = array(
    'variables' => array(),
    'template' => 'footer_custom',
  );

  $themes['bs'] = array(
    'variables' => array(),
    'template' => 'search_button',
  );

  $themes['slogan'] = array(
    'variables' => array(),
    'template' => 'slogan',
  );

  $themes['block_course_finder'] = array(
    'variables' => array(),
    'template' => 'block_course_finder',
  );

  $themes['block_alumni_things'] = array(
    'variables' => array(),
    'template' => 'block_alumni_things',
  );

  $themes['block_about_right'] = array(
    'variables' => array(),
    'template' => 'block_about_right',
  );

  $themes['block_sort_people'] = array(
    'variables' => array(),
    'template' => 'block_sort_people',
  );

  $themes['block_contact_left_side'] = array(
    'variables' => array(),
    'template' => 'block_contact_left_side',
  );

  return $themes;
}

function university_permission() {
  return array(
    'get ajax' => array(
      'title' => t('How are get ajax data'),
      'description' => t('Get ajax data'),
    )
  );
}
